name: Deploy Dynamic HTML Documentation to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ $default-branch ]
    paths: [ "openapi.yaml" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # Use LTS version of Java instead of 21 which might not be supported everywhere

      - name: Install OpenAPI Generator CLI
        run: |
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.3.0/openapi-generator-cli-5.3.0.jar -O openapi-generator-cli.jar

      - name: Generate Documentation Using OpenAPI Generator
        run: java -jar openapi-generator-cli.jar generate -i openapi.yaml -g dynamic-html -o docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
