name: Manage GitHub Pages Configuration

on:
  workflow_dispatch:
  # Trigger manually, or you can set this to trigger on other events.

jobs:
  check-and-update-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check and Update GitHub Pages Configuration
        uses: actions/github-script@v6
        with:
          script: |
            // Fetch GitHub Pages configuration
            const pagesConfig = await github.rest.repos.getPages({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            console.log('Current Pages Configuration:', pagesConfig.data);

            // If Pages are not setup to deploy from 'main' branch and '/docs' folder, update them
            if (pagesConfig.data.source.branch !== 'main' || pagesConfig.data.source.path !== '/docs') {
              const updateResponse = await github.rest.repos.updateInformationAboutPagesSite({
                owner: context.repo.owner,
                repo: context.repo.repo,
                source: {
                  branch: 'main',
                  path: '/docs'
                }
              });

              console.log('Updated Pages Configuration:', updateResponse.data);
            } else {
              console.log('No update needed, Pages are configured correctly.');
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
