name: Manage GitHub Pages Configuration

on:
  workflow_dispatch:
  # Trigger manually, or you can set this to trigger on other events.

jobs:
  check-and-update-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check and Update GitHub Pages Configuration
        uses: actions/github-script@v7
        with:
          script: |
            const org = 'containerly'; // Replace with your organization name
            
            // Fetch all repositories in the organization
            const repos = await github.paginate(github.rest.repos.listForOrg, {
              org: org,
              type: 'public' // Change to 'all' to include private repositories
            });
            
            for (const repo of repos) {
              try {
                // Fetch the current GitHub Pages configuration
                const pagesConfig = await github.rest.repos.getPages({
                  owner: org,
                  repo: repo.name
                });
            
                // Check if the GitHub Pages are configured to deploy from the 'main' branch and '/docs' folder
                if (!pagesConfig.source || pagesConfig.source.branch !== 'main' || pagesConfig.source.path !== '/docs') {
                  // Update the configuration if it's not set correctly
                  await github.rest.repos.updateInformationAboutPagesSite({
                    owner: org,
                    repo: repo.name,
                    source: {
                      branch: 'main',
                      path: '/docs'
                    }
                  });
            
                  console.log(`Updated Pages configuration for ${repo.name}`);
                } else {
                  console.log(`GitHub Pages already configured correctly for ${repo.name}`);
                }
              } catch (error) {
                // Handle possible errors, such as no Pages setup on the repository
                console.error(`Error accessing/updating Pages for ${repo.name}: ${error.message}`);
              }
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
