name: Manage GitHub Pages Configuration

on:
  workflow_dispatch:

jobs:
  check-and-update-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check and Update GitHub Pages Configuration
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.pages_rw }}
          script: |
            const org = 'containerly'; // Replace with your organization name
            
            // Fetch all repositories in the organization
            const repos = await github.paginate(github.rest.repos.listForOrg, {
              org: org,
              type: 'public' // Change to 'all' to include private repositories
            });
            
            for (const repo of repos) {
              try {
                // Fetch the current GitHub Pages configuration
                const pagesConfig = await github.rest.repos.getPages({
                  owner: org,
                  repo: repo.name
                });
            
                // Check if the GitHub Pages are configured to deploy from the 'main' branch and '/docs' folder
                if (!pagesConfig.source || pagesConfig.source.branch !== 'main' || pagesConfig.source.path !== '/docs') {
                  // Update the configuration if it's not set correctly
                  await github.rest.repos.updateInformationAboutPagesSite({
                    owner: org,
                    repo: repo.name,
                    source: {
                      branch: 'main',
                      path: '/docs'
                    }
                  });
            
                  console.log(`Updated Pages configuration for ${repo.name}`);
                } else {
                  console.log(`GitHub Pages already configured correctly for ${repo.name}`);
                }
              } catch (error) {
                if (error.status === 404) {
                  console.log(`GitHub Pages not set up for ${repo.name}, setting up now...`);
                  // Set up GitHub Pages if not already set up
                  await github.rest.repos.createPagesSite({
                    owner: org,
                    repo: repo.name,
                    source: {
                      branch: "main",
                      path: "/docs"
                    }
                  });
                  console.log(`GitHub Pages setup completed for ${repo.name}`);
                  continue;
                } else {
                  throw error; // Rethrow other errors that we don't handle
                }
              }
            }
